name: Run Unit/Integration Tests for app.py

on:
  push:
    branches:
      - main  # Runs on pushes to main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the test environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls your code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"  # Use the Python version of your project

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt 

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s . -p "test_*.py"